/* tslint:disable */
/* eslint-disable */
/**
 * Documentation
 * api documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface LoginUserResponseExampleUser
 */
export interface LoginUserResponseExampleUser {
  /**
   *
   * @type {number}
   * @memberof LoginUserResponseExampleUser
   */
  userId: number;
  /**
   *
   * @type {string}
   * @memberof LoginUserResponseExampleUser
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof LoginUserResponseExampleUser
   */
  password: string;
}
