/* tslint:disable */
/* eslint-disable */
/**
 * Documentation
 * api documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RolesResponse
 */
export interface RolesResponse {
    /**
     * 
     * @type {number}
     * @memberof RolesResponse
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof RolesResponse
     */
    'name': string;
}

