/* tslint:disable */
/* eslint-disable */
/**
 * Documentation
 * api documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SchedulePerson
 */
export interface SchedulePerson {
  /**
   *
   * @type {string}
   * @memberof SchedulePerson
   */
  firstName: string;
  /**
   *
   * @type {string}
   * @memberof SchedulePerson
   */
  middleName: string;
  /**
   *
   * @type {string}
   * @memberof SchedulePerson
   */
  lastName: string;
}
